// index.html lo Generate button click ayinappudu
function goNext() {
  // Input field nundi YouTube link tiskuntam
  const link = document.getElementById("link").value;

  // Empty input check
  if (link.trim() === "") {
    alert("Please paste a YouTube link");
    return;
  }

  // Link ni temporary ga store cheyyadam
  localStorage.setItem("videoLink", link);

  // Second page ki navigate cheyyadam
  window.location.href = "summary.html";
}


// summary.html load ayinappudu link show cheyyadam
document.addEventListener("DOMContentLoaded", function () {
  const showLink = document.getElementById("showLink");

  if (showLink) {
    showLink.innerText = localStorage.getItem("videoLink");
  }
});


// Chatbox lo message add cheyyadam (UI only)
function sendMessage() {
  const input = document.getElementById("question");
  const chatBox = document.getElementById("chatbox");

  if (input.value.trim() === "") return;

  // User message
  const userMsg = document.createElement("div");
  userMsg.className = "user";
  userMsg.innerText = "You: " + input.value;
  chatBox.appendChild(userMsg);

  // Dummy bot reply
  const botMsg = document.createElement("div");
  botMsg.className = "bot";
  botMsg.innerText = "EduTube AI: This answer will be generated by backend.";
  chatBox.appendChild(botMsg);

  input.value = "";
}
